### ISSUE TITLE
Link to Stylus documentation explaining block mixins

### ISSUE THREAD

**Issue by daniellealexis** [Lukavyi/stylus-input-placeholder-mixin#3]
Thank you for the plugin. I think the README could be improved by explaining WHY the '+' is necessary. Here's a link to the Stylus documentation for it: http://stylus-lang.com/docs/mixins.html#block-mixins

**Comment by Lukavyi** [comment]
Thanks for feedback, glad you like my mixin.
I'll add the info you've requested.
